---
title: "Part 1 - Stringr Functions"
author: "Anna Talken"
date: "2/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Detect string patterns `str_detect()`

```{r}
#create messy string data in a vector
vec <- c(" A Unicorn   Fish ", "add  cornmeal", "french fries  ", "acorn squash  ")

str_detect(vec, pattern = "corn") #recognizes pattern in elements of a vector
```


```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk")) #looks through every entry in name column and selects anything that contains walk in it

walk_subset

#Use str_subset()
```

### Replace a string pattern with something else

`str_replace()` to replace an existing string pattern with something else

```{r}
vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL") #replaced 'corn' with 'COOL' in all elements in a certain string
```

replace the pattern "Sky" with the pattern "TORNADO"

```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))
```

## Use `str_trim()` to remove excess leading and trailing whitespace

```{r}
str_trim(vec)

str_squish(vec) #removes excess whitespace in the MIDDLE of a string
```

```{r}
str_detect(vec, pattern = "Corn") #str_detect doesn't recognize capitalized 'Corn'
```

- `str_to_*()`

```{r}
str_to_lower(vec) #converts string to lowercase

str_to_upper(vec) #converts string to uppercase
```

Using these in combination:

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "Llama")) %>% 
  mutate(name = str_to_lower(name))
```












